# Generated by Django 4.0.1 on 2022-01-05 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_item_category_item_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price_after_disc',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.IntegerField(default=120),
        ),
    ]
