# Generated by Django 4.0.1 on 2022-01-05 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_item_price_after_disc_alter_item_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price_after_disc',
            field=models.IntegerField(default=0),
        ),
    ]
