# Generated by Django 4.0.1 on 2022-01-05 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_item_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='item',
            new_name='items',
        ),
    ]
