# Generated by Django 4.0.1 on 2022-01-06 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price_after_disc',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
